package com.eli.calc.shape.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-11T19:20:47.050-04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.service.shape.calc.eli.com/", name = "ShapeCalculatorWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ShapeCalculatorWebService {

    @WebMethod
    @RequestWrapper(localName = "getPendingRequests", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.GetPendingRequests")
    @ResponseWrapper(localName = "getPendingRequestsResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.GetPendingRequestsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.PendingRequestsResponse getPendingRequests();

    @WebMethod
    @RequestWrapper(localName = "deletePendingRequests", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.DeletePendingRequests")
    @ResponseWrapper(localName = "deletePendingRequestsResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.DeletePendingRequestsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.StatusResponse deletePendingRequests();

    @WebMethod
    @RequestWrapper(localName = "getCalculatedResults", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.GetCalculatedResults")
    @ResponseWrapper(localName = "getCalculatedResultsResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.GetCalculatedResultsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.CalculatedResultsResponse getCalculatedResults();

    @WebMethod
    @RequestWrapper(localName = "queueCalculation", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.QueueCalculation")
    @ResponseWrapper(localName = "queueCalculationResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.QueueCalculationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.StatusResponse queueCalculation(
        @WebParam(name = "QueueCalculationParms", targetNamespace = "")
        com.eli.calc.shape.service.ws.QueueCalculationParms queueCalculationParms
    );

    @WebMethod
    @RequestWrapper(localName = "deleteResults", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.DeleteResults")
    @ResponseWrapper(localName = "deleteResultsResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.DeleteResultsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.StatusResponse deleteResults();

    @WebMethod
    @RequestWrapper(localName = "runPendingRequestsStopOnError", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.RunPendingRequestsStopOnError")
    @ResponseWrapper(localName = "runPendingRequestsStopOnErrorResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.RunPendingRequestsStopOnErrorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.RunPendingRequestsResponse runPendingRequestsStopOnError();

    @WebMethod
    @RequestWrapper(localName = "runPendingRequestsNoStopOnError", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.RunPendingRequestsNoStopOnError")
    @ResponseWrapper(localName = "runPendingRequestsNoStopOnErrorResponse", targetNamespace = "http://ws.service.shape.calc.eli.com/", className = "com.eli.calc.shape.service.ws.RunPendingRequestsNoStopOnErrorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.eli.calc.shape.service.ws.RunPendingRequestsResponse runPendingRequestsNoStopOnError();
}
